go_import_path: github.com/emccode/polly

before_install:
  - git config --global 'url.https://gopkg.in/yaml.v1.insteadof' 'https://gopkg.in/yaml.v1/'
  - git config --global 'url.https://gopkg.in/yaml.v2.insteadof' 'https://gopkg.in/yaml.v2/'
  - git config --global 'url.https://gopkg.in/fsnotify.v1.insteadof' 'https://gopkg.in/fsnotify.v1/'
  - git config --global 'url.https://github.com/.insteadof' 'git://github.com/'
  - git config --global 'url.https://github.com/.insteadof' 'git@github.com:'

language: go

go:
  - 1.x

addons:
  apt:
    packages:
    - rpm

before_script:
  - source .build/dependencies.sh

script:
  - POLLY_DEBUG=true LIBSTORAGE_DEBUG=true make deps build-all test rpm-all deb-all deploy-prep

notifications:
  - slack: $SLACK_BUILDS

before_deploy:
  - .build/bintray-decapitate.sh

deploy:
  - provider: bintray
    file: .build/bintray-stupid-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^$ && ($TRAVIS_REPO_SLUG = 'emccode/polly' || $IGNORE_REPO_SLUG_CONDITION = true) && ($TRAVIS_BRANCH = master || $IGNORE_BRANCH_CONDITION = true)

  - provider: bintray
    file: .build/bintray-staged-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ -rc[[:digit:]]+$ && ($TRAVIS_REPO_SLUG = 'emccode/polly' || $IGNORE_REPO_SLUG_CONDITION = true)

  - provider: bintray
    file: .build/bintray-stable-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]$ && ($TRAVIS_REPO_SLUG = 'emccode/polly' || $IGNORE_REPO_SLUG_CONDITION = true)

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  apt: true
  directories:
    - $HOME/.opt
